name: DreamCraft
main: com.mrsweeter.dreamcraft.DreamCraft
version: 2.0
author: MrSweeter / SweetDream
description: Modify / Remove / Add crafts recipes

commands:
    dcrreload:
        description: Reload config !
        usage: §c/dcrreload
        permission: dreamcraft.reload
    dcrhelp:
        description: Show help !
        usage: §c/dcrhelp
        aliases: dcr
        permission: dreamcraft.help